import type { CourtCase, ReviewRecord, Department, ActivityItem, DeadlineItem } from '@/types';

export const departments: Department[] = [
  { id: '1', name: 'Public Works Department', shortCode: 'PWD', totalCases: 45, pendingActions: 12, overdueActions: 3, complianceRate: 78 },
  { id: '2', name: 'Revenue Department', shortCode: 'REV', totalCases: 38, pendingActions: 8, overdueActions: 2, complianceRate: 82 },
  { id: '3', name: 'Municipal Corporation', shortCode: 'MCD', totalCases: 52, pendingActions: 15, overdueActions: 5, complianceRate: 71 },
  { id: '4', name: 'Health Department', shortCode: 'HLT', totalCases: 28, pendingActions: 6, overdueActions: 1, complianceRate: 89 },
  { id: '5', name: 'Education Department', shortCode: 'EDU', totalCases: 33, pendingActions: 9, overdueActions: 2, complianceRate: 85 },
  { id: '6', name: 'Forest Department', shortCode: 'FOR', totalCases: 22, pendingActions: 5, overdueActions: 1, complianceRate: 88 },
  { id: '7', name: 'Home Department', shortCode: 'HOM', totalCases: 41, pendingActions: 11, overdueActions: 4, complianceRate: 74 },
  { id: '8', name: 'Urban Development', shortCode: 'URB', totalCases: 36, pendingActions: 10, overdueActions: 3, complianceRate: 76 },
];

export const courtCases: CourtCase[] = [
  {
    id: 'WP-2024-00134',
    caseNumber: 'WP/2024/00134',
    courtName: 'Delhi High Court',
    benchName: 'Division Bench - II',
    judgeName: "Hon'ble Justice R.K. Sharma",
    dateOfOrder: '2024-01-15',
    petitioner: 'Rajesh Kumar Singh',
    respondent: 'State of Delhi & Ors.',
    department: 'Public Works Department',
    status: 'active',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2024-01-16',
    deadlineDate: '2024-02-15',
    judgment: {
      id: 'j1',
      caseId: 'WP-2024-00134',
      rawPdfUrl: '/judgments/wp-2024-00134.pdf',
      ocrText: 'IN THE HIGH COURT OF DELHI AT NEW DELHI...',
      extractedFields: [],
      summary: 'Court directed the PWD to complete road repair work within 30 days and submit compliance report.',
      keyDirections: [
        'Complete road repair work within 30 days',
        'Submit compliance report with photographic evidence',
        'Ensure proper drainage system installation'
      ],
      mentionedDeadlines: [{ description: 'Road repair completion', date: '2024-02-15', daysRemaining: 5, isUrgent: true }],
      departmentsInvolved: ['PWD', 'MCD'],
      finalDecision: 'Petition Allowed',
      confidenceScore: 94,
      extractedAt: '2024-01-16'
    },
    actionPlan: {
      id: 'ap1',
      caseId: 'WP-2024-00134',
      actionType: 'compliance',
      priority: 'high',
      responsibleDepartment: 'Public Works Department',
      responsibleOfficer: 'Er. Suresh Verma',
      lastDateForAction: '2024-02-15',
      summary: 'Complete road repair and drainage installation as per court directions.',
      suggestedSteps: [
        'Survey damaged road sections',
        'Procure materials for repair',
        'Execute repair work',
        'Install drainage system',
        'Submit compliance report with photos'
      ],
      status: 'in_progress',
      approvedBy: 'Dr. Amit Sharma',
      approvedAt: '2024-01-18'
    }
  },
  {
    id: 'CWP-1892-2023',
    caseNumber: 'CWP-1892-2023',
    courtName: 'Punjab & Haryana High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice M.S. Sandhu",
    dateOfOrder: '2023-12-20',
    petitioner: 'Gurpreet Singh Dhillon',
    respondent: 'State of Punjab',
    department: 'Revenue Department',
    status: 'overdue',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2023-12-21',
    deadlineDate: '2024-01-20',
    judgment: {
      id: 'j2',
      caseId: 'CWP-1892-2023',
      rawPdfUrl: '/judgments/cwp-1892-2023.pdf',
      ocrText: 'IN THE HIGH COURT OF PUNJAB AND HARYANA...',
      extractedFields: [],
      summary: 'Court ordered land record correction within 30 days with compensation to petitioner.',
      keyDirections: [
        'Correct land records within 30 days',
        'Pay compensation of Rs. 50,000 to petitioner',
        'Issue corrected ownership certificate'
      ],
      mentionedDeadlines: [{ description: 'Land record correction', date: '2024-01-20', daysRemaining: -15, isUrgent: true }],
      departmentsInvolved: ['Revenue'],
      finalDecision: 'Petition Allowed with Costs',
      confidenceScore: 91,
      extractedAt: '2023-12-22'
    },
    actionPlan: {
      id: 'ap2',
      caseId: 'CWP-1892-2023',
      actionType: 'compliance',
      priority: 'high',
      responsibleDepartment: 'Revenue Department',
      responsibleOfficer: 'Sh. Harinder Pal Singh',
      lastDateForAction: '2024-01-20',
      summary: 'Urgent: Land record correction and compensation payment overdue.',
      suggestedSteps: [
        'Verify land records',
        'Process correction in revenue records',
        'Release compensation payment',
        'Issue corrected certificate'
      ],
      status: 'overdue'
    }
  },
  {
    id: 'SLP-C-4421-2024',
    caseNumber: 'SLP(C) 4421/2024',
    courtName: 'Supreme Court of India',
    benchName: 'Three Judge Bench',
    judgeName: "Hon'ble Justice D.Y. Chandrachud, CJI",
    dateOfOrder: '2024-02-01',
    petitioner: 'Union of India',
    respondent: 'Environmental Action Group',
    department: 'Forest Department',
    status: 'appeal',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2024-02-02',
    deadlineDate: '2024-03-15',
    judgment: {
      id: 'j3',
      caseId: 'SLP-C-4421-2024',
      rawPdfUrl: '/judgments/slp-4421-2024.pdf',
      ocrText: 'IN THE SUPREME COURT OF INDIA...',
      extractedFields: [],
      summary: 'Supreme Court directed comprehensive environmental impact assessment before forest clearance.',
      keyDirections: [
        'Conduct fresh Environmental Impact Assessment',
        'Public hearing mandatory',
        'Submit report to NGT within 45 days'
      ],
      mentionedDeadlines: [{ description: 'EIA submission', date: '2024-03-15', daysRemaining: 30, isUrgent: false }],
      departmentsInvolved: ['Forest', 'Environment'],
      appealObservation: 'Matter requires detailed examination of environmental concerns.',
      finalDecision: 'SLP Admitted - Notice Issued',
      confidenceScore: 96,
      extractedAt: '2024-02-03'
    },
    actionPlan: {
      id: 'ap3',
      caseId: 'SLP-C-4421-2024',
      actionType: 'appeal',
      priority: 'high',
      responsibleDepartment: 'Forest Department',
      responsibleOfficer: 'Dr. Priya Mehta, IFS',
      lastDateForAction: '2024-03-15',
      summary: 'Coordinate EIA study and prepare counter affidavit for Supreme Court.',
      suggestedSteps: [
        'Engage certified EIA consultant',
        'Conduct site survey',
        'Organize public hearing',
        'Compile EIA report',
        'File counter affidavit'
      ],
      status: 'in_progress',
      approvedBy: 'Sh. Vikram Singh, IAS',
      approvedAt: '2024-02-05'
    }
  },
  {
    id: 'WP-C-7823-2024',
    caseNumber: 'W.P.(C) 7823/2024',
    courtName: 'Delhi High Court',
    benchName: 'Division Bench - I',
    judgeName: "Hon'ble Justice S.P. Garg",
    dateOfOrder: '2024-01-28',
    petitioner: 'Residents Welfare Association, Dwarka',
    respondent: 'Delhi Jal Board',
    department: 'Municipal Corporation',
    status: 'active',
    priority: 'medium',
    reviewStatus: 'pending_review',
    createdAt: '2024-01-29',
    deadlineDate: '2024-02-28',
    judgment: {
      id: 'j4',
      caseId: 'WP-C-7823-2024',
      rawPdfUrl: '/judgments/wp-7823-2024.pdf',
      ocrText: 'IN THE HIGH COURT OF DELHI...',
      extractedFields: [],
      summary: 'Court directed immediate water supply restoration and infrastructure upgrade.',
      keyDirections: [
        'Restore regular water supply within 7 days',
        'Repair leaking pipelines within 30 days',
        'Install water meters in all connections'
      ],
      mentionedDeadlines: [
        { description: 'Water supply restoration', date: '2024-02-05', daysRemaining: -5, isUrgent: true },
        { description: 'Pipeline repair', date: '2024-02-28', daysRemaining: 18, isUrgent: false }
      ],
      departmentsInvolved: ['MCD', 'DJB'],
      finalDecision: 'Petition Allowed',
      confidenceScore: 89,
      extractedAt: '2024-01-30'
    }
  },
  {
    id: 'WP-2023-15678',
    caseNumber: 'WP/2023/15678',
    courtName: 'Bombay High Court',
    benchName: 'Division Bench',
    judgeName: "Hon'ble Justice A.S. Gadkari",
    dateOfOrder: '2023-11-15',
    petitioner: 'Maharashtra Teachers Association',
    respondent: 'State of Maharashtra',
    department: 'Education Department',
    status: 'complied',
    priority: 'medium',
    reviewStatus: 'approved',
    createdAt: '2023-11-16',
    deadlineDate: '2023-12-15',
    judgment: {
      id: 'j5',
      caseId: 'WP-2023-15678',
      rawPdfUrl: '/judgments/wp-2023-15678.pdf',
      ocrText: 'IN THE HIGH COURT OF BOMBAY...',
      extractedFields: [],
      summary: 'Court directed release of pending salary arrears to teachers within 30 days.',
      keyDirections: [
        'Release pending salary arrears',
        'Submit compliance affidavit',
        'No disciplinary action against protesting teachers'
      ],
      mentionedDeadlines: [{ description: 'Salary disbursement', date: '2023-12-15', daysRemaining: 0, isUrgent: false }],
      departmentsInvolved: ['Education', 'Finance'],
      finalDecision: 'Petition Disposed',
      confidenceScore: 93,
      extractedAt: '2023-11-17'
    },
    actionPlan: {
      id: 'ap5',
      caseId: 'WP-2023-15678',
      actionType: 'compliance',
      priority: 'medium',
      responsibleDepartment: 'Education Department',
      responsibleOfficer: 'Dr. Neeta Kulkarni',
      lastDateForAction: '2023-12-15',
      summary: 'Process and disburse pending salary arrears as per court order.',
      suggestedSteps: [
        'Calculate arrears for all affected teachers',
        'Obtain budget sanction',
        'Process payment',
        'File compliance affidavit'
      ],
      status: 'completed',
      approvedBy: 'Sh. Ashok Patil, IAS',
      approvedAt: '2023-11-20'
    }
  },
  {
    id: 'WP-2024-00892',
    caseNumber: 'WP/2024/00892',
    courtName: 'Madras High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice K. Ravichandran",
    dateOfOrder: '2024-01-10',
    petitioner: 'Tamil Nadu Medical Association',
    respondent: 'State of Tamil Nadu',
    department: 'Health Department',
    status: 'complied',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2024-01-11',
    deadlineDate: '2024-02-10',
    judgment: {
      id: 'j6',
      caseId: 'WP-2024-00892',
      rawPdfUrl: '/judgments/wp-2024-00892.pdf',
      ocrText: 'IN THE HIGH COURT OF MADRAS...',
      extractedFields: [],
      summary: 'Court mandated upgrade of medical equipment in district hospitals within 30 days.',
      keyDirections: [
        'Procure essential medical equipment',
        'Ensure proper maintenance schedule',
        'Submit quarterly status reports'
      ],
      mentionedDeadlines: [{ description: 'Equipment procurement', date: '2024-02-10', daysRemaining: 0, isUrgent: false }],
      departmentsInvolved: ['Health'],
      finalDecision: 'Petition Disposed with Directions',
      confidenceScore: 92,
      extractedAt: '2024-01-12'
    },
    actionPlan: {
      id: 'ap6',
      caseId: 'WP-2024-00892',
      actionType: 'compliance',
      priority: 'high',
      responsibleDepartment: 'Health Department',
      responsibleOfficer: 'Dr. S. Ramanathan',
      lastDateForAction: '2024-02-10',
      summary: 'Procure and install medical equipment in all district hospitals.',
      suggestedSteps: [
        'Prepare equipment list',
        'Float tenders',
        'Complete procurement',
        'Install and commission equipment'
      ],
      status: 'completed',
      approvedBy: 'Dr. P. Venkatesh, IAS',
      approvedAt: '2024-01-15'
    }
  },
  {
    id: 'CWP-2024-3456',
    caseNumber: 'CWP/2024/3456',
    courtName: 'Punjab & Haryana High Court',
    benchName: 'Division Bench',
    judgeName: "Hon'ble Justice G.S. Sandhawalia",
    dateOfOrder: '2024-01-25',
    petitioner: 'Haryana State Road Transport',
    respondent: 'NHAI & Ors.',
    department: 'Urban Development',
    status: 'active',
    priority: 'medium',
    reviewStatus: 'pending_review',
    createdAt: '2024-01-26',
    deadlineDate: '2024-02-25',
  },
  {
    id: 'WP-2024-01234',
    caseNumber: 'WP/2024/01234',
    courtName: 'Delhi High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice N. Kotiswar Singh",
    dateOfOrder: '2024-02-01',
    petitioner: 'Delhi Police Welfare Association',
    respondent: 'Ministry of Home Affairs',
    department: 'Home Department',
    status: 'active',
    priority: 'high',
    reviewStatus: 'pending_review',
    createdAt: '2024-02-02',
    deadlineDate: '2024-03-01',
  },
  {
    id: 'WP-2023-98765',
    caseNumber: 'WP/2023/98765',
    courtName: 'Bombay High Court',
    benchName: 'Division Bench',
    judgeName: "Hon'ble Justice R.D. Dhanuka",
    dateOfOrder: '2023-10-20',
    petitioner: 'Mumbai Suburban Railway Users',
    respondent: 'Western Railway',
    department: 'Urban Development',
    status: 'complied',
    priority: 'low',
    reviewStatus: 'approved',
    createdAt: '2023-10-21',
    deadlineDate: '2023-11-20',
  },
  {
    id: 'WP-2024-05678',
    caseNumber: 'WP/2024/05678',
    courtName: 'Madras High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice S. Vimala",
    dateOfOrder: '2024-01-18',
    petitioner: 'Tamil Nadu Farmers Association',
    respondent: 'State of Tamil Nadu',
    department: 'Revenue Department',
    status: 'overdue',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2024-01-19',
    deadlineDate: '2024-02-02',
  },
  {
    id: 'SLP-C-8892-2024',
    caseNumber: 'SLP(C) 8892/2024',
    courtName: 'Supreme Court of India',
    benchName: 'Two Judge Bench',
    judgeName: "Hon'ble Justice B.R. Gavai",
    dateOfOrder: '2024-02-05',
    petitioner: 'State of Karnataka',
    respondent: 'Environment Protection Council',
    department: 'Forest Department',
    status: 'appeal',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2024-02-06',
    deadlineDate: '2024-03-20',
  },
  {
    id: 'WP-2024-02345',
    caseNumber: 'WP/2024/02345',
    courtName: 'Delhi High Court',
    benchName: 'Division Bench',
    judgeName: "Hon'ble Justice V.K. Rao",
    dateOfOrder: '2024-01-22',
    petitioner: 'Delhi University Teachers',
    respondent: 'University of Delhi',
    department: 'Education Department',
    status: 'active',
    priority: 'medium',
    reviewStatus: 'approved',
    createdAt: '2024-01-23',
    deadlineDate: '2024-02-22',
  },
  {
    id: 'CWP-2023-7654',
    caseNumber: 'CWP/2023/7654',
    courtName: 'Punjab & Haryana High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice A.K. Mittal",
    dateOfOrder: '2023-12-10',
    petitioner: 'Punjab PWD Contractors',
    respondent: 'State of Punjab',
    department: 'Public Works Department',
    status: 'overdue',
    priority: 'medium',
    reviewStatus: 'approved',
    createdAt: '2023-12-11',
    deadlineDate: '2024-01-10',
  },
  {
    id: 'WP-2024-03456',
    caseNumber: 'WP/2024/03456',
    courtName: 'Bombay High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice S.J. Kathawalla",
    dateOfOrder: '2024-01-30',
    petitioner: 'BMC Workers Union',
    respondent: 'MCGM',
    department: 'Municipal Corporation',
    status: 'active',
    priority: 'low',
    reviewStatus: 'needs_edit',
    createdAt: '2024-01-31',
    deadlineDate: '2024-03-01',
  },
  {
    id: 'WP-2024-04567',
    caseNumber: 'WP/2024/04567',
    courtName: 'Madras High Court',
    benchName: 'Division Bench',
    judgeName: "Hon'ble Justice N. Kirubakaran",
    dateOfOrder: '2024-02-03',
    petitioner: 'Chennai Citizens Forum',
    respondent: 'Chennai Corporation',
    department: 'Municipal Corporation',
    status: 'active',
    priority: 'medium',
    reviewStatus: 'pending_review',
    createdAt: '2024-02-04',
    deadlineDate: '2024-03-05',
  },
  {
    id: 'WP-2024-05789',
    caseNumber: 'WP/2024/05789',
    courtName: 'Delhi High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice P.S. Teji",
    dateOfOrder: '2024-02-06',
    petitioner: 'Delhi Resident Doctors',
    respondent: 'AIIMS Administration',
    department: 'Health Department',
    status: 'active',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2024-02-07',
    deadlineDate: '2024-03-06',
  },
  {
    id: 'WP-2023-45678',
    caseNumber: 'WP/2023/45678',
    courtName: 'Bombay High Court',
    benchName: 'Division Bench',
    judgeName: "Hon'ble Justice B.P. Colabawalla",
    dateOfOrder: '2023-09-15',
    petitioner: 'Maharashtra Home Guards',
    respondent: 'State of Maharashtra',
    department: 'Home Department',
    status: 'complied',
    priority: 'medium',
    reviewStatus: 'approved',
    createdAt: '2023-09-16',
    deadlineDate: '2023-10-15',
  },
  {
    id: 'CWP-2024-1234',
    caseNumber: 'CWP/2024/1234',
    courtName: 'Punjab & Haryana High Court',
    benchName: 'Division Bench',
    judgeName: "Hon'ble Justice A. Bawa",
    dateOfOrder: '2024-02-08',
    petitioner: 'Chandigarh Housing Board',
    respondent: 'UT Administration',
    department: 'Urban Development',
    status: 'active',
    priority: 'low',
    reviewStatus: 'approved',
    createdAt: '2024-02-09',
    deadlineDate: '2024-03-08',
  },
  {
    id: 'WP-2024-06789',
    caseNumber: 'WP/2024/06789',
    courtName: 'Madras High Court',
    benchName: 'Single Bench',
    judgeName: "Hon'ble Justice M. Sundar",
    dateOfOrder: '2024-01-05',
    petitioner: 'Tamil Nadu Revenue Officers',
    respondent: 'State of Tamil Nadu',
    department: 'Revenue Department',
    status: 'overdue',
    priority: 'high',
    reviewStatus: 'approved',
    createdAt: '2024-01-06',
    deadlineDate: '2024-01-20',
  },
];

export const reviewRecords: ReviewRecord[] = [
  {
    id: 'rev-001',
    caseId: 'WP-C-7823-2024',
    caseName: 'RWA Dwarka vs Delhi Jal Board',
    extractionId: 'j4',
    assignedTo: 'Sh. Rakesh Kumar',
    status: 'pending_review',
    submittedAt: '2024-01-30',
    confidenceScore: 89,
    fieldsCount: 12,
    deadline: '2024-02-28',
  },
  {
    id: 'rev-002',
    caseId: 'CWP-2024-3456',
    caseName: 'HSRTC vs NHAI',
    extractionId: 'j7',
    assignedTo: 'Smt. Anita Sharma',
    status: 'pending_review',
    submittedAt: '2024-01-27',
    confidenceScore: 72,
    fieldsCount: 10,
    deadline: '2024-02-25',
  },
  {
    id: 'rev-003',
    caseId: 'WP-2024-01234',
    caseName: 'Delhi Police vs MHA',
    extractionId: 'j8',
    assignedTo: 'Dr. Priya Mehta',
    status: 'pending_review',
    submittedAt: '2024-02-03',
    confidenceScore: 85,
    fieldsCount: 14,
    deadline: '2024-03-01',
  },
  {
    id: 'rev-004',
    caseId: 'WP-2024-04567',
    caseName: 'Chennai Citizens vs Corporation',
    extractionId: 'j15',
    assignedTo: 'Sh. V. Ramasamy',
    status: 'pending_review',
    submittedAt: '2024-02-05',
    confidenceScore: 68,
    fieldsCount: 11,
    deadline: '2024-03-05',
  },
  {
    id: 'rev-005',
    caseId: 'WP-2024-00134',
    caseName: 'Rajesh Kumar vs State',
    extractionId: 'j1',
    assignedTo: 'Sh. Amit Verma',
    status: 'approved',
    submittedAt: '2024-01-17',
    reviewedAt: '2024-01-18',
    reviewerNotes: 'All fields verified. Action plan approved.',
    confidenceScore: 94,
    fieldsCount: 13,
    editsMade: 0,
  },
  {
    id: 'rev-006',
    caseId: 'WP-2024-03456',
    caseName: 'BMC Workers vs MCGM',
    extractionId: 'j14',
    assignedTo: 'Smt. Prachi Desai',
    status: 'needs_edit',
    submittedAt: '2024-02-01',
    reviewerNotes: 'Deadline date needs correction. Please verify respondent name.',
    confidenceScore: 78,
    fieldsCount: 12,
    editsMade: 2,
  },
];

export const recentActivities: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'approved',
    description: 'Case WP/2024/00134 action plan approved',
    timestamp: '2024-02-10T14:30:00',
    user: { name: 'Dr. Amit Sharma', initials: 'AS' },
    caseNumber: 'WP/2024/00134',
  },
  {
    id: 'act-2',
    type: 'deadline_alert',
    description: 'Deadline approaching for CWP-1892-2023',
    timestamp: '2024-02-10T12:00:00',
    user: { name: 'System', initials: 'SY' },
    caseNumber: 'CWP-1892-2023',
  },
  {
    id: 'act-3',
    type: 'uploaded',
    description: 'New judgment uploaded for W.P.(C) 7823/2024',
    timestamp: '2024-02-10T10:15:00',
    user: { name: 'Smt. Anita Sharma', initials: 'AS' },
    caseNumber: 'W.P.(C) 7823/2024',
  },
  {
    id: 'act-4',
    type: 'review_started',
    description: 'Review started for WP/2024/01234',
    timestamp: '2024-02-10T09:45:00',
    user: { name: 'Dr. Priya Mehta', initials: 'PM' },
    caseNumber: 'WP/2024/01234',
  },
  {
    id: 'act-5',
    type: 'rejected',
    description: 'Case WP/2024/03456 sent back for edits',
    timestamp: '2024-02-09T16:30:00',
    user: { name: 'Smt. Prachi Desai', initials: 'PD' },
    caseNumber: 'WP/2024/03456',
  },
  {
    id: 'act-6',
    type: 'approved',
    description: 'Case SLP(C) 4421/2024 action plan approved',
    timestamp: '2024-02-09T14:00:00',
    user: { name: 'Sh. Vikram Singh', initials: 'VS' },
    caseNumber: 'SLP(C) 4421/2024',
  },
  {
    id: 'act-7',
    type: 'uploaded',
    description: 'New judgment uploaded for CWP/2024/1234',
    timestamp: '2024-02-09T11:30:00',
    user: { name: 'Sh. Harinder Pal', initials: 'HP' },
    caseNumber: 'CWP/2024/1234',
  },
  {
    id: 'act-8',
    type: 'deadline_alert',
    description: 'URGENT: Deadline passed for WP/2024/05678',
    timestamp: '2024-02-09T09:00:00',
    user: { name: 'System', initials: 'SY' },
    caseNumber: 'WP/2024/05678',
  },
];

export const upcomingDeadlines: (DeadlineItem & { caseNumber: string; department: string; actionType: string })[] = [
  { caseNumber: 'WP/2024/00134', department: 'PWD', description: 'Road repair completion', date: '2024-02-15', daysRemaining: 5, isUrgent: true, actionType: 'Compliance' },
  { caseNumber: 'CWP-1892-2023', department: 'Revenue', description: 'Land record correction', date: '2024-01-20', daysRemaining: -15, isUrgent: true, actionType: 'Compliance' },
  { caseNumber: 'W.P.(C) 7823/2024', department: 'MCD', description: 'Pipeline repair', date: '2024-02-28', daysRemaining: 18, isUrgent: false, actionType: 'Compliance' },
  { caseNumber: 'WP/2024/02345', department: 'Education', description: 'Faculty appointment', date: '2024-02-22', daysRemaining: 12, isUrgent: false, actionType: 'Review' },
  { caseNumber: 'WP/2024/01234', department: 'Home', description: 'Welfare scheme implementation', date: '2024-03-01', daysRemaining: 19, isUrgent: false, actionType: 'Compliance' },
  { caseNumber: 'SLP(C) 4421/2024', department: 'Forest', description: 'EIA submission', date: '2024-03-15', daysRemaining: 33, isUrgent: false, actionType: 'Appeal' },
  { caseNumber: 'WP/2024/05789', department: 'Health', description: 'Stipend disbursement', date: '2024-03-06', daysRemaining: 24, isUrgent: false, actionType: 'Compliance' },
  { caseNumber: 'CWP/2024/1234', department: 'Urban Dev', description: 'Housing allotment', date: '2024-03-08', daysRemaining: 26, isUrgent: false, actionType: 'Internal Order' },
  { caseNumber: 'WP/2024/04567', department: 'MCD', description: 'Sanitation audit', date: '2024-03-05', daysRemaining: 23, isUrgent: false, actionType: 'Compliance' },
  { caseNumber: 'SLP(C) 8892/2024', department: 'Forest', description: 'Counter affidavit', date: '2024-03-20', daysRemaining: 38, isUrgent: false, actionType: 'Appeal' },
];

export const dashboardStats = {
  totalActiveCases: 147,
  pendingReview: 4,
  upcomingDeadlines: 10,
  complianceRate: 78,
  casesTrend: [120, 125, 130, 142, 147],
};

export const complianceChartData = [
  { name: 'Complied', value: 85, color: '#1A7A4A' },
  { name: 'Pending', value: 42, color: '#D4891A' },
  { name: 'Overdue', value: 12, color: '#C0392B' },
  { name: 'Under Review', value: 8, color: '#3B82F6' },
];

export const monthlyTrendData = [
  { month: 'Sep', cases: 95 },
  { month: 'Oct', cases: 108 },
  { month: 'Nov', cases: 120 },
  { month: 'Dec', cases: 115 },
  { month: 'Jan', cases: 132 },
  { month: 'Feb', cases: 147 },
];

export const departmentComplianceData = departments.map(d => ({
  name: d.shortCode,
  compliance: d.complianceRate,
  pending: d.pendingActions,
  overdue: d.overdueActions,
}));
